spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
               cpu: "0.5"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          env:
          - name: JAVA_OPTIONS
            value: -XX:NativeMemoryTracking=summary -XX:MaxRAM=512m
